//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransactionalVariable {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TransactionalVariable.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only read-only transactions can be started from within a read-only transaction..
        /// </summary>
        internal static string BeginReadWriteInReadonlyTransaction {
            get {
                return ResourceManager.GetString("BeginReadWriteInReadonlyTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This exception is thrown as part of the normal operation. It must be ignored..
        /// </summary>
        internal static string ConflictAbortation {
            get {
                return ResourceManager.GetString("ConflictAbortation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This exception seems to be caused by an internal bug. Please fill a bug report..
        /// </summary>
        internal static string InternalError {
            get {
                return ResourceManager.GetString("InternalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attempted operation requires an active transaction..
        /// </summary>
        internal static string OutsideOfTransaction {
            get {
                return ResourceManager.GetString("OutsideOfTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attempted operation is not allowed within a read-only transaction..
        /// </summary>
        internal static string ReadOnlyTransaction {
            get {
                return ResourceManager.GetString("ReadOnlyTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value has failed the validation..
        /// </summary>
        internal static string ValidationFailed {
            get {
                return ResourceManager.GetString("ValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value could not be assigned to the variable since it did not pass the validation..
        /// </summary>
        internal static string VariableValidationFailed {
            get {
                return ResourceManager.GetString("VariableValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No variables can be assigned to during a read-only transaction..
        /// </summary>
        internal static string WriteInReadonlyTransaction {
            get {
                return ResourceManager.GetString("WriteInReadonlyTransaction", resourceCulture);
            }
        }
    }
}
